### ISSUE TITLE
Dracula Theme

### ISSUE THREAD

**Issue by RobLoach** [casonadams/base16-darcula-scheme#1]
While this was originally inspired by the Dracula Theme in JetBrains, could it be re-worked for https://draculatheme.com ?

The colors are pretty similar....
![Screenshot from 2024-07-17 12-13-41](https://github.com/user-attachments/assets/48965969-c4cf-4098-9f99-446324e2bcc9)

**Comment by casonadams** [comment]
Sure! Are you interested in doing the work and open a pull request?

**Comment by casonadams** [comment]
Actually sorry I missed spoke. Darcula is not Dracula. They are different schemes

**Comment by RobLoach** [comment]
Ah, my dyslexia has gotten me again :fist_raised:
